name: Update Posts Cron

on:
  schedule:
    - cron: '*/30 * * * *' # Запуск каждые 30 минут
  workflow_dispatch: # Позволяет запустить вручную через кнопку

jobs:
  run-parser:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install telethon supabase requests

      - name: Run parser task
        env:
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          TG_SESSION_STRING: ${{ secrets.TG_SESSION_STRING }}
          SUPABASEE_URL: ${{ secrets.SUPABASEE_URL }}
          SUPABASEE_KEY: ${{ secrets.SUPABASEE_KEY }}
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }} # ДОБАВИЛИ КЛЮЧ ИИ
        run: python task_runner.py
